version: '3.8'

services:
  kaban-front:
    build:
      context: ./kaban-front
    restart: unless-stopped
    depends_on:
      - kaban-nest-service

  kaban-nest-service:
    build:
      context: ./kaban-nest-service
    container_name: kaban-nest-service
    env_file:
      - ./configs/nest-service/.prod.env
    restart: unless-stopped
    depends_on:
      postgres-nest:
        condition: service_healthy
      redis:
        condition: service_started

  postgres-nest:
    image: postgres:16
    container_name: postgres-nest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Strong!Pass123"
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_nest_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kaban-go-auth-service:
    build:
      context: ./kaban-go-auth-service
    container_name: kaban-go-auth-service
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./configs/go-auth/config.yaml:/app/config/config.yaml
    restart: unless-stopped
    depends_on:
      postgres-auth:
        condition: service_healthy

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_USER: sso_user
      POSTGRES_PASSWORD: sso_db_password
      POSTGRES_DB: sso
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_INITDB_LOCALE: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      TZ: "UTC"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sso_user -d sso"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kaban-go-service:
    build:
      context: ./kaban-go-service
    container_name: kaban-go-service
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./configs/go-service/config.yaml:/app/config/config.yaml
    restart: unless-stopped

  directus:
    image: directus/directus:latest
    container_name: directus
    environment:
      DB_CLIENT: pg
      DB_CONNECTION_STRING: postgres://postgres:Strong!Pass123@postgres-nest:5432/mydatabase
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: "Admin!Pass123"
      PUBLIC_URL: "https://kaban.inkycrane.space/directus"
    depends_on:
      postgres-nest:
        condition: service_healthy
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: "https://kaban.inkycrane.space/minio-console"
      MINIO_SERVER_URL: "https://kaban.inkycrane.space/minio"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=https://kaban.inkycrane.space/prometheus'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://kaban.inkycrane.space/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_nest_data:
  postgres_auth_data:
  minio_data:
  prometheus_data:
  grafana_data:
